### ISSUE TITLE
Compose mutliplatform support

### ISSUE THREAD

**Issue by WhosNickDoglio** [j-roskopf/ComposeGuard#28]
The plugin currently  _seems_ to only registers tasks when `com.android.library` or `com.android.application` plugins are applied but it would be great if it supported Compose on other platforms.

**Comment by j-roskopf** [comment]
I took a stab at adding rudimentary support for multiplatform here - https://github.com/j-roskopf/ComposeGuard/pull/29

I added a sandbox multiplatform app to play around with. Going to continue to work on it a bit, but let me know if you have any feedback!

**Comment by j-roskopf** [comment]
@WhosNickDoglio I think the current PR is in a good state to merge now, so i'm going to close the issue. The plugin now supports android / desktop / ios / js (wasm / IR). I'll release a 2.0 shortly after merging and doing some more validation
