### ISSUE TITLE
compiler-metrics.md link is outdated

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#35]
When throwing errors, plugin will mention https://github.com/androidx/androidx/blob/androidx-main/compose/compiler/design/compiler-metrics.md link which is now dead

New link: https://github.com/JetBrains/kotlin/blob/master/plugins/compose/design/compiler-metrics.md

**Comment by j-roskopf** [comment]
awesome! will address shortly, thank you

**Comment by j-roskopf** [comment]
Pushed out release 2.2.0 to maven central with this fix
