### ISSUE TITLE
ComposeGuard will read all reports from compose_reports folder, leading to false positives

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#36]
Steps to reproduce:

1. Open example `sandbox-android-app` project
2. Disable strong skipping
3. Run `debugComposeCompilerCheck`
4. Run `releaseComposeCompilerCheck`

BUG: Check will fail with the `New Composables were added that are restartable but not skippable!` error, even though no Composable was added.

From my analysis, it seems the problem is that plugin will indiscriminately read all files from `compose_reports` folder. That folder will in above case contain both `app_release-composables.txt` and `app_debug-composables.txt`, which means that existing composables will get read twice, leading to a false positive, since number of read composables is now higher than number saved in the report.

**Comment by j-roskopf** [comment]
![Screenshot 2024-07-05 at 9 10 33 AM](https://github.com/j-roskopf/ComposeGuard/assets/7951665/6749300a-137c-4403-9276-36f17b8e4673)

good catch! thank you for the report. I have updated the tasks to only use that variant for the reports. if no variants exists (running `debugComposeCompilerCheck` even though `debugComposeCompilerGenerate` hasn't been run yet), you'll now get the following error message

**Comment by j-roskopf** [comment]
Pushed out release 2.2.0 to maven central with this fix

**Comment by matejdro** [comment]
Thank you!
