### ISSUE TITLE
Feature request: allow execution without golden metrics

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#53]
Currently, running check task will fail, when there are no golden metrics.

Could we change it so that without golden metrics, it can still run, but just reporting every unstable Composable (without baseline)?

**Comment by j-roskopf** [comment]
I think that's reasonable, but would probably defer that to be opt in behavior. 

```
composeGuardCheck {
    reportAllOnMissingBaseline = true // defaults to false
} 
```

If enabled, the check task will now aggregate all errors and display them with a failure

<img width="1578" alt="Screenshot 2024-08-27 at 7 44 25 AM" src="https://github.com/user-attachments/assets/716569af-e60f-4f18-b527-7a1d560ba128">

**Comment by j-roskopf** [comment]
will push out 2.3.2 with that behavior

**Comment by matejdro** [comment]
Hm, it seems that with 2.3.2, setting `reportAllOnMissingBaseline` to true will cause ComposeGuard to ignore the baseline, even if it is present

**Comment by j-roskopf** [comment]
That was how I envisioned this request working and what I added to the documentation in the readme. 

```
    /**
     * If baseline metrics are missing, the check task will no longer fail and will instead just report
     * all checks. Baseline metrics will be effectively ignored when this is set.
     */
    reportAllOnMissingBaseline = true // defaults to false
```

my assumption was when this was enabled, there would never be golden metrics. Is that not the case? for some modules you have golden metrics and some not?

**Comment by matejdro** [comment]
> for some modules you have golden metrics and some not

Yes. On our older modules, we have golden metrics, because of legacy code that is not 100% stable yet. But for any new modules, we want 100% stability, so there is no need for golden metrics.

**Comment by j-roskopf** [comment]
but even in new modules that have 100% stability, the golden metrics would still serve a purpose of listing all of your composables with that 100% stability. if a developer is working in that new module, and accidentally adds an unstable parameter or something, the plugin would flag. is there a reason you'd want to avoid just generating the golden metrics for all modules?

**Comment by matejdro** [comment]
For new modules, they are empty at start. So golden metrics that I would generate would be empty. And even if they wouldn't, having just stable composable in golden metrics, is essentially identical to having no golden metrics at all, right?

**Comment by j-roskopf** [comment]
fair! I'll push the behavior up in 2.3.3 shortly

**Comment by matejdro** [comment]
Seems to be working well. Thanks!

**Comment by matejdro** [comment]
Hm, found a pretty big issue with having no metrics:

When removing the metrics folder, `genExtension.outputDirectory` will be empty, which will cause all kotlin tasks to never be up to date: https://github.com/j-roskopf/ComposeGuard/blob/d966181e0471cd6548b77aa6cd83204a1879bef5/compose-guard/gradle-plugin/src/main/kotlin/com/joetr/compose/guard/ReportGenPlugin.kt#L224

this essentially disables incremental compilation for modules without metrics

**Comment by j-roskopf** [comment]
I have added a check to make sure the user has run the write or check task as well to address the issue. will go out in 2.3.5

**Comment by matejdro** [comment]
Seems to be working fine on 2.3.5. Thanks!
