### ISSUE TITLE
ComposeGuard still sets upToDateWhen even when configureKotlinTasks is disabled

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#58]
https://github.com/j-roskopf/ComposeGuard/blob/d966181e0471cd6548b77aa6cd83204a1879bef5/compose-guard/gradle-plugin/src/main/kotlin/com/joetr/compose/guard/ReportGenPlugin.kt#L220 I think this block should be moved below inside the if check?

**Comment by j-roskopf** [comment]
Whoops! I had missed that configuration. Will push out shortly in 2.3.5

**Comment by matejdro** [comment]
Seems to be working fine on 2.3.5. Thanks!
