### ISSUE TITLE
Gradle fails when running compose guard and KSP tasks of different flavors at the same time

### ISSUE THREAD

**Issue by matejdro** [j-roskopf/ComposeGuard#65]
When running compose guard check and KSP tasks of different flavors at the same time (for example debug compose check + release KSP build), Gradle will fail with the following error:

```
1: Task failed with an exception.
-----------
* What went wrong:
A problem was found with the configuration of task ':feature:debugComposeCompilerCheck' (type 'ComposeCompilerReportCheckTask').
  - Gradle detected a problem with the following location: '/.../sandbox-android-app/feature/build/generated/ksp/release/kotlin/com/example/myapplication/feature/TestDataClass$$DeepCopy.kt'.
    
    Reason: Task ':feature:debugComposeCompilerCheck' uses this output of task ':feature:kspReleaseKotlin' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':feature:kspReleaseKotlin' as an input of ':feature:debugComposeCompilerCheck'.
      2. Declare an explicit dependency on ':feature:kspReleaseKotlin' from ':feature:debugComposeCompilerCheck' using Task#dependsOn.
      3. Declare an explicit dependency on ':feature:kspReleaseKotlin' from ':feature:debugComposeCompilerCheck' using Task#mustRunAfter.
    
    For more information, please refer to https://docs.gradle.org/8.10.2/userguide/validation_problems.html#implicit_dependency in the Gradle documentation.
```

This can only be reproduced on fairly recent Gradle versions, which might explain why it was not noticed in this sample project, which is on fairly old Gradle 8.2.

Steps to reproduce:

1. Open `sandbox-android-app` project in this repo
2. Update Gradle to 8.10.2
3. Run `./gradlew debugComposeCompilerCheck kspReleaseKotlin`

I think the issue may stem from the fact that ComposeGuard depends on `project.getKotlinSources()` which includes all kotlin sources (both debug and release) instead of just kotlin sources that are relevant to its flavor.

**Comment by j-roskopf** [comment]
pushed out 2.4.0 with a fix. thank you for the report!
