### ISSUE TITLE
Spotless configuration is inefficient

### ISSUE THREAD

**Issue by nedtwigg** [j-roskopf/ComposeGuard#67]
https://github.com/j-roskopf/ComposeGuard/blob/76832270f989df4f0a7a51b4308a7b3913500567/compose-guard/build.gradle.kts#L26-L30

This would be much more efficient: `target('src/**/*.kt')`. It lets you remove the `targetExclude`, and it will search a smaller set of files. We have tried to remove all leading `**/*.blah` from our examples, because there's almost always some prefix that can make things a lot faster.

**Comment by j-roskopf** [comment]
ah! good to know. thank you for the info! I've updated the configuration in the following PR https://github.com/j-roskopf/ComposeGuard/pull/68
